import baryshevskyi from '@/assets/images/kyiv-geneva/select-jury/baryshevskyi.webp';
import dvarionas from '@/assets/images/kyiv-geneva/select-jury/dvarionas.webp';
import kikuchi from '@/assets/images/kyiv-geneva/select-jury/kikuchi.webp';
import meerovitch from '@/assets/images/kyiv-geneva/select-jury/meerovitch.webp';
import szymanowski from '@/assets/images/kyiv-geneva/select-jury/szymanowski.webp';

export const content = {
  list: [
    {
      id: 'baryshevskyi',
      name: {
        ua: 'Антоній Баришевський',
        en: 'Antonii Baryshevskyi',
      },
      photo: baryshevskyi,
      text: {
        ua: '«У Баришевського є щось особливе, особливий талант. Як на мене, він мав би бути нагороджений першою премією». \n Марта Аргеріх  \n Антоній Баришевський народився у Києві. Навчався у Дитячій музичній школі №14 ім. Дмитра Кабалевського, де його першими вчительками були Аліна Соркіна та Рита Донська. \n Продовжив навчання у Київській спеціалізованій музичній школі ім. Миколи Лисенка. Після її завершення у 2007 році вступив до Національної музичної академії України ім. Петра Чайковського, де навчався і проходив асистентуру-стажування у класі професора Валерія Козлова. У 2013-2015 роках навчався у Паризькій музичній школі ім. Альфреда Корто у класі професора Маріана Рибіцкі. \n Брав участь у майстеркласах Альфреда Бренделя, Даніеля Поллака, Річарда Гуда та Лілі Дорфман. \n Лауреат понад 30 міжнародних конкурсів, серед яких: конкурс піаністів ім. Олександра Скрябіна (І премія, 2020, м. Гроссето, Італія); конкурс майстрів фортепіано ім. Артура Рубінштейна (І премія, 2014, м. Тель-Авів, Ізраїль); конкурс піаністів ім. Ферруччо Бузоні (II премія, 2011, м. Больцано, Італія); конкурс піаністів Prize «Jaén» (I премія, 2009, м. Хаен, Іспанія); конкурс піаністів ISAM (І премія, 2006, Німеччина); Міжнародний конкурс піаністів пам’яті Володимира Горовиця (II премія, 2005, м. Київ, Україна). \n Брав участь у міжнародних фестивалях: Рурзький фортепіанний фестиваль (2012, 2014, Німеччина), Проєкт Марти Аргеріх (2014, м. Лугано, Швейцарія), фестиваль ім. Ферруччо Бузоні (2012, м. Больцано, Італія), Проєкт MusicaInsieme Fondazione (м. Болонья, 2017; м. Варіньяна, 2018 – Італія), музичний літній фестиваль MDR Musicsommer Festival (2015, м. Айзенах, Німеччина) тощо. \n Постійно виступає із сольними концертами та у супроводі симфонічних оркестрів в Україні та за кордоном. Грав із провідними європейськими колективами, зокрема: оркестром Мюнхенського радіо, оркестром Ізраїльської філармонії, оркестром Гейдельберзької філармонії, Гранадським міським оркестром. Виступав із оркестрами під керівництвом диригентів Ашера Фіша, Фредеріка Шазлена, Говарда Ґріффітса, Дугласа Бостока, Герда Альбрехта, Романа Кофмана, Маркуса Боша, Валентина Урюпіна, Оксани Линів, Кирила Карабиця та багатьох інших. \n Гастролював майже в усіх країнах Європи, а також в Ізраїлі, Марокко, Південній Кореї, США та Японії. \n Антоній здійснив записи на радіо й телебаченні України, Данії, Іспанії, Італії, Сербії. \n Наразі він запрошений професор Музичної академії «Давідсбюндлер» у м. Гаага (Нідерланди)',
        en: 'Antonii Baryshevskyi is a Ukrainian pianist born in Kyiv. He graduated from the National Music Academy of Ukraine. Among his teachers were Alina Sorkina, Ryta Donska, and Valerii Kozlov. Also, he graduated from Ecole Normale de musique de Paris, where he studied with Marian Rybicki. He participated in the Master Classes with Profs. Daniel Pollack, Lily Dorfman, Alfred Brendel and others. Antonii is a prize-winner of many international piano contests, such as the Arthur Rubinstein International Piano Master Competition and the F. Busoni International Piano Competition. He was a participant in the Progetto Martha Argerich, Klavier Ruhr festival, Busoni festival, projects by Musica Insieme Fondazione, and others. He has recorded for numerous CD labels, including Naxos as well as radio and TV productions of the Italian, Danish, Spanish, German, and many other Radio-Television agencies. He is a guest professor at Davidsbündler Music Academy in Den Haag.',
      },
    },
    {
      id: 'dvarionas',
      name: {
        ua: 'Юстас Дваріонас',
        en: 'Justas Dvarionas',
      },
      photo: dvarionas,
      text: {
        ua: 'Професійна майстерність та яскрава індивідуальність піаніста вперше отримали міжнародне визнання на Міжнародному конкурсі піаністів «Virtuosi per Musica di Pianoforte» у Чехословаччині, де у віці 11 років він із тріумфом представляв свою країну й повернувся додому, в Литву, зірковим лауреатом. Згодом із відзнакою закінчив Московську державну консерваторію ім. П. І. Чайковського, де навчався у Льва Власенка та Михайла Плетньова. \n Ще під час навчання став переможцем та призером багатьох міжнародних конкурсів, серед яких – Міжнародний конкурс піаністів ім. Віотті (Італія), Міжнародний конкурс піаністів у місті Порту (Португалія), Міжнародний конкурс піаністів ім. М. Чюрльоніса (Литва). Піаніст веде активну концертну діяльність – виступає з сольними концертами, виконує камерну музику, грає у супроводі оркестрів Болгарії, Канади, Німеччини, Росії, США, Швеції, Норвегії, Греції, Австрії, Перу, Великої Британії, Японії тощо. \n Плідно поєднує виконавську діяльність із педагогічною роботою; є асоційованим професором Музичної академії Університету ім. Вітаутаса Магнуса, запрошується до роботи у Школі ім. Персела у Лондоні та викладає у Вищій школі мистецтв ім. М. Чюрльоніса у Вільнюсі. Постійно проводить майстеркласи у Німеччині, Польщі, Норвегії, Франції, Росії, Японії, Перу, Великій Британії, Литві, Італії та інших країнах. Багато з його студентів стали володарями головних призів престижних міжнародних фортепіанних конкурсів. \n Член журі багатьох міжнародних конкурсів піаністів, серед яких: конкурс ім. Джини Бахауер (США), Орхуський конкурс у Данії, юнацький конкурс ім. Ф. Ліста (Німеччина), телевізійний конкурс «Лускунчик» (Росія), ім. М. Рубінштейна (Франція), конкурс «Концертіно Прага» (Чехія), конкурс Володимира Крайнєва (Україна), конкурс «Санта Чечілія» у м. Порту (Португалія), конкурс ім. Р. Шумана (Німеччина) та багато інших.  \n З 2008 року Юстаc Дваріонас є віцепрезидентом EMCY – Європейської спілки молодіжних музичних конкурсів.',
        en: 'Justas Dvarionas is Associated Professor at the Vytautas Magnus University Music Academy and is Visiting Piano Teacher at The Purcell School in London. He has also held many Master Classes own in Germany, Poland, Norway, France, Russia, Japan, Australia, Italy, Peru, Great Britain, Lithuania and numerous other countries. Many of his students have been awarded major prizes at prestigious piano competitions. Since 2008 Justas Dvarionas is Vice-President of EMCY (European Union of Music Competitions for Youth). \n He has served as jury member in many international competitions (like the Gina Bachauer Piano Competition, USA; Aarhus International Piano Competition, Denmark; Liszt Junior Piano Competition, Germany; N.Rubinstein International Piano Competition, France; Pyabhang Sanitwongse Piano Competition, Thailand; International Radio Competition for Young Musicians \'Concertino Praga\', Czech Republic; Volodymyr Krainev Competition, Ukraine; Competition for Young Pianists in Memory of Vladimir Horowitz, Ukraine; Santa Cecilia International Competition Porto, Portugal; PIANALE Competition, Germany, R.Schumann Junior Competition, Germany and many others). \n Justas’ studies began in his native Lithuania and lead him to the Moscow P.Tchaikovsky Conservatoire for graduate and post-graduate studies, both of which he completed with highest honours (CUM LAUDE) studying under Prof Lev Vlassenko and Mikhail Pletnev. Justas\' pianistic and musical abilities were enhanced through his acquaintances with pianist Sviatoslav Richter and Elisso Wirssaladse. \n During his final years of study, he won the Italian "Viotti-Valsesia" International Piano Competition in 1992. Justas also received special awards from both the Portuguese "Porto" International Piano Competition and the "International M.K. Čiurlionis" Piano Competition in Lithuania, meriting the respect of jury chairman Daniel Pollack: "Justas Dvarionas from Lithuania left me with one of the biggest impressions...[he] has unique interpretation”',
      },
    },
    {
      id: 'kikuchi',
      name: {
        ua: 'Йоко Кікуті',
        en: 'Yoko Kikuchi',
      },
      photo: kikuchi,
      text: {
        ua: 'Народилася в Японії. У 1996 році переїхала до Італії, де закінчила Міжнародну академію фортепіано «Incontri col Maestro» м. Імола (класи Франко Скала та Стефано Фьюцці). \n У 2002 році здобула першу премію на Міжнародному конкурсі ім. Моцарта у Зальцбурзі. З того часу виступала з багатьма оркестрами Азії та Європи. \n Співпрацювала з відомими диригентами, зокрема Лоуренсом Фостером, Айвором Болтоном, Ютакою Садо, Гердом Альбрехтом, Деннісом Расселом Девісом, Лейфом Сегерстамом, Гайнцом Карлом Грубером, Педро Альфтером, Крістіаном Армінгом, Деном Еттінгером та іншими. Як камерна виконавиця Йоко постійно виступає з валторністом Радеком Бабораком, фаготистом Даніеле Даміано, скрипалем Райнером Гонеком, контрабасистом Едіксоном Руїзом. \n Грала з такими оркестрами, як: філармонічний оркестр радіо Ганновера, оркестр «Gulbenkian», симфонічний оркестр NHK, оркестр Mozarteum у Зальцбурзі, камерний оркестр ім. Ференца Ліста, Національний симфонічний оркестр Аргентини, симфонічний оркестр Бретані, камерний оркестр Мантови, симфонічні оркестри Шанхаю, Гонконгу, Шеньчженя та усі японські оркестри тощо. \n Брала участь у ряді міжнародних музичних фестивалів: Зальцбурзькому фестивалі, Шлезвіґ-Гольштайнському музичному фестивалі, Празькій весні та Флорентійському музичному травні, тощо. \n Захоплюючись іншими видами мистецтва, вона співпрацювала з артистами класичного балету, серед яких Світлана Захарова, Діана Вишнева, Марсело Гомеш, Алессандра Феррі, Міяко Йошіда та інші. \n Її дебютний компакт-диск із творами Моцарта був відзначений премії на 18-й церемонії нагородження Премії Music Pen Club як «Найкращий запис японського виконавця»; з того часу піаністка випустила ще десять компакт-дисків. \n Йоко Кікуті проживає у Відні, Сієні та Токіо.',
        en: 'YOKO was born in Japan. In 1996 she moved to Italy in order to complete her studies at the “Incontri col Maestro” International Piano Academy in Imola (Franco Scala, and fortepiano with Stefano Fiuzzi) \n In 2002, she won the first prize at the International Mozart Competition in Salzburg, since then she has performed with major orchestra in Asia and in Europe. \n Yoko has performed with many conductors including Lawrence Foster, Ivor Bolton, Yutaka Sado, Gerd Albrecht, Dennis Russell Davis, Leif Segerstam, HK Gruber ,Pedro Halffter, Christian Arming, Dan Ettinger among others. In the field of chamber music, Yoko regularly collaborates with hornist Radek Baborak, bassoon player Daniele Damiano, violinist Rainer Honeck, double bass player Edicson Ruiz. \n She has performed with the NDR Radio Philharmonie Orchester Hannover , Gulbenkian Orchestra, NHK Symphony Orchestra, Mozarteum Orchestra Salzburg, Franz Liszt Chamber Orchestra, Orchesta Sinfonica National Argentina, Orchestra Symphonique de Bretagne, Orchestra da Camera di Mantova, Shanghai Symphony Orchestra, Hong Kong Sinfonietta, Shenzhen Symphony Orchestra, all Japanese Orchestras and others. \n She also participated in several music festivals such as Salzburg Festival, Prague Spring Festival, Schleswig-Holstein Musik Festival, Maggio Musicale Fiorentino and others. \n Yoko is also passionate about other forms of art and she collaborated with classical ballet dancers including Svetlana Zakharova, Diana Vishneva, Marcelo Gomes, Alessandra Ferri, Miyako Yoshida and others. \n Her debut CD (Mozart) was awarded the 18th Music Pen Club Prize"Best Recording by a Japanese Artist". Since then ten more CDs have been released. YOKO is living in Vienna , in Siena and in Tokyo.',
      },
    },
    {
      id: 'meerovitch',
      name: {
        ua: 'Марія Меєрович',
        en: 'Maria Meerovich',
      },
      photo: meerovitch,
      text: {
        ua: 'Бельгійська піаністка Марія Меєрович народилася у Санкт-Петербурзі. Музика була важливою частиною життя її родини. У 6 років вона почала навчатися грі на фортепіано, у вісім – вперше виступила у Санкт-Петербурзькій філармонії. \n Навчалася на молодшому відділенні Санкт-Петербурзької державної консерваторії ім. Миколи Римського-Корсакова у професорів М. Фрейндлінга та М. Лебедя, потім – у класі фортепіано професора Анатолія Угорського. \n У 1990 році, отримавши стипендію від фонду Ю. Менухіна, переїхала до Бельгії. З відзнакою закінчила Королівську консерваторію в Антверпені, де почала викладати у класах фортепіано та камерної музики. \n Здобула перші нагороди декількох міжнародних конкурсів, серед яких Міжнародний музичний конкурс імені Дж. Віотті (Італія) та Міжнародний конкурс камерної музики імені Ч. Хеннена (Нідерланди). \n З того часу виступає з сольними та камерними концертами у США, Японії, Тайвані, Бразилії, Південно-Африканській Республіці, Південній Кореї, Ізраїлі та у Європі. Її концерти відбувалися у залі Консертґебау (Амстердам), на Бад-Кіссінгенському музичному фестивалі, Шлезвіґ-Гольштайнському музичному фестивалі, Транссибірському фестивалі мистецтв у Новосибірську, Паризькому музичному фестивалі, а також у залах Opera City Hall у Токіо, Laeiszhalle у Гамбурзі, на Ньюпортському музичному фестивалі, Міжнародному музичному фестивалі ім. Станіслава Дворжака у Празі тощо. \n Виступала з численними оркестрами по всьому світу, серед яких: Лондонський філармонічний, Штутгартський камерний, Національний симфонічний оркестр Тайваню, фестивальний оркестр Шлезвіґ-Гольштайну, Англійський камерний оркестр, філармонічний оркестр радіо Німеччини та багато інших. \n Марія – авторка дослідження про лікування важкого тендиніту у професійних піаністів. Розроблені нею вправи, засновані на власному досвіді, мають ефект повного одужання. Результат цих досліджень суттєво позначилися на її повсякденній викладацькій роботі. \n Значний резонанс серед професійних музикантів отримали нині лекції Марії на тему страху сцени, основані на власному дослідженні піаністки.',
        en: 'Belgian pianist Maria Meerovitch was born in St.Petersburg to non-musicians family. Nevertheless music has been an important part of family’s life and at the age of six Maria began her musical education. At the age of eight she performed at St.Petersburg Philharmonic Hall for the first time. She continued her studies at St.Petersburg Conservatory’s junior Music Institute with M.Freindling and M.Lebed and later under Prof. Anatol Ugorski at the Rimsky- Korsakov St.Petersburg State Conservatory, with piano as principal subject. \n In 1990 Maria came to Belgium after having received a scholarship from “Fonds Alex de Vries”- Y.Menuhin Foundation, graduated from the Royal Conservatory of Antwerp (cum laude) and immediately began teaching piano and chamber music at the same institution. She subsequently won first prizes at several International Competitions (G.B. Viotti, Italy; Ch. Hennen, the Netherlands) and has been performing around the world ever since appearing in solo and chamber music recitals in the USA, Japan, Taiwan, Brazil, The Republic of South Africa, South Korea, Israel and Europe. Highlights include Concertgebouw (Amsterdam), Bad-Kissingen Musik Festival, Schleswig-Holstein Musik Festival, Trans Siberian Art Festival (Novosibirsk), Cité de la Musique (Paris), Opera City Hall (Tokyo), Laeiszhalle (Hamburg), Newport Music Festival (Newport), Dvorák International Music Festival (Prague), among others. \n As a soloist Maria appeared with numerous orchestras around the globe including London Philharmonic Orchestra, Stuttgart Chamber Orchestra, Taiwan National Symphony Orchestra, Schleswig-Holstein Festival Orchestra, The English Chamber Orchestra, Deutsche Radio Philharmonie, and many others. \n Maria’s research on a subject related to the treatment of severe tendonitis during the piano playing amongst professional musicians, a list of exercises, based on her own experience and full recovery, made a significant change in her daily work as a piano instructor. Her present lectures on a subject connected to a “Stage Fright” research has received a significant response from professional musicians.',
      },
    },
    {
      id: 'szymanowski',
      name: {
        ua: 'Міхал Шимановський',
        en: 'Michal Szymanowsky',
      },
      photo: szymanowski,
      text: {
        ua: 'Польський піаніст і диригент Міхал Шимановський народився 1988 року у родині музикантів. У сім років почав вчитися грі на фортепіано у Державній музичній школі ім. Артура Рубінштейна у Бидгощі, де протягом 12 років вдосконалював свої навички у класі професорки Людмили Касьяненко. З відзнакою закінчив Музичну академію у Бидгощі у класах фортепіано професорки Катажини Попової-Зидронь та симфонічно-оперного диригування професора Зигмунта Рихерта. Підвищував свою майстерність під керівництвом професора Ельдара Небольсіна у Вищій школі музики ім. Ганса Айслера у Берліні. Наразі викладає фортепіано у своїй альма-матер, займає посаду доцента. \n Здобув найвищі нагороди багатьох національних та міжнародних конкурсів піаністів, зокрема: конкурсу польської музики ім. Станіслава Монюшка у Жешуві (2021, Польща), конкурсу піаністів ім. Фридерика Шопена у Дармштадті (2017, Німеччина), конкурсу піаністів MozARTè в Аахені (2016, Німеччина), конкурсу ім. Фридерика Шопена в Тегу (2015, Корея), музичного конкурсу ім. Юліуша Зарембського у Варшаві (2012, Польща), конкурсу Yamaha у м. Катовіце (2011, Польща), конкурсу ім. Ігнація Яна Падеревського у Бидгощі (2010, Польща), конкурсу молодих піаністів пам’яті Володимира Горовиця у Києві (2007, Україна). У 2015 році представляв Польщу на 17-му Міжнародному конкурсі піаністів ім. Фридерика Шопена у Варшаві. \n Виступав у США, Японії, Бразилії, Аргентині та Венесуелі; грав у Палаці Націй у Женеві, Залі Павла VI у Ватикані (концерт на честь Папи Бенедикта XVI), у варшавському палаці Бельведер на честь президента Польщі та неодноразово виступав на фестивалі «Шопен і його Європа» у Варшаві, де він блискуче виконав фортепіанні концерти Падеревського, Венявського та Стойовського. \n У здобутку виконавця два сольні альбоми для CD Accord (Naxos) із творами Шопена, Падеревського, Шимановського та Венявського, які отримали схвальні відгуки музичних критиків. Зокрема, один із рецензентів написав про Міхала Шимановського: «Незвичайний талант і перспективний піаніст».',
        en: 'A Polish pianist and conductor, Michał Karol Szymanowski was born in 1988 into a musical family. He began his musical education and formal piano training at the age of seven at the Arthur Rubinstein State Music Schools in Bydgoszcz where, for 12 years, he sharpened his skills under the guidance of Ludmila Kasjanenko. He graduated with honours from the Academy of Music in Bydgoszcz, where he studied piano with Katarzyna Popowa-Zydroń and symphonic-operatic conducting under Zygmunt Rychert. He honed his skills with Eldar Nebolsin at the Hochschule für Musik Hanns Eisler in Berlin. At present he works as an assistant professor at his alma mater, teaching the piano. \n Michał has won top awards in a number of national and international piano competitions, including: Moniuszko International Competition of Polish Music in Rzeszów (2021), International Chopin Piano Competition in Darmstadt, Germany (2017), MozARTè International Piano Competition in Aachen, Germany (2016), Chopin Competition in Daegu, Korea (2015), Zarębski International Music Competition in Warsaw (2012), Yamaha Competition in Katowice (2011), Paderewski Competition in Bydgoszcz (2010), Horowitz Competition in Kiev (2007). In 2015 he represented Poland at the 17th International Chopin Piano Competition in Warsaw. \n Michał has given performances in USA, Japan, Brazil, Argentina and Venezuela. He has performed in the Palace of Nations in Geneva, the Paul VI Audience Hall in the Vatican \n (a concert for Pope Benedict XVI), at Warsaw’s Belvedere Palace for Polish President, and 4 times at the “Chopin and His Europe” Festival in Warsaw, where he brilliantly performed piano concertos by Paderewski, Wieniawski and Stojowski. \n Michał has released two solo albums for CD Accord (Naxos), featuring compositions by Chopin, Paderewski, Szymanowski and Wieniawski. The recordings were critically acclaimed. One reviewer wrote: “Uncommon talent and a pianist of great promise.”',
      },
    },
  ],
};
