export const initialState = {
  isLoading: false,
  requestLang: '',
  isCommonDataFetched: false,
  isActiveConditions: false,
  isActiveJury: false,
  isActivePreselectionJury: false,
  isActiveTimetable: false,
  isActiveRequirements: false,
  isActiveParticipants: false,
  isActiveRewards: false,
  isActiveOrchestra: false,
  isActiveWinners: false,
  isActiveVenues: false,
  isActiveGuests: false,
  isActiveBooklet: false,

  conditions: null,
  requirements: null,
  timetable: null,
  venues: null,
  rewards: null,
  prizes: null,
  artists: null,
  jury: null,
  guests: null,
  booklet: null,
  winnersGallery: null,
  winners: null,
};
